"""sync-latest-models

Revision ID: 2baed539aea6
Revises: c6af9cf25a25
Create Date: 2026-08-25 15:54:14.891766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2baed539aea6'
down_revision: Union[str, Sequence[str], None] = 'c6af9cf25a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('preference', sa.INTEGER(), autoincrement=False, nullable=False, comment='喜好度，默认为 0'))
    # ### end Alembic commands ###
