"""2026年8月20日17:16:19

Revision ID: c6af9cf25a25
Revises: 322269570dd2
Create Date: 2026-08-20 17:16:20.706299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6af9cf25a25'
down_revision: Union[str, Sequence[str], None] = '322269570dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('preference', sa.Integer(), nullable=False, comment='喜好度，默认为 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'preference')
    # ### end Alembic commands ###
